test:
  track:
    exp_name: &TEST_NAME "siamfcpp_googlenet"
    exp_save: &TEST_SAVE "logs"
    model:
      backbone:
        name: "Inception3"
        Inception3:
          crop_pad: 4
          pruned: True
      losses:
        names: []
      task_head:
        name: "DenseboxHead"
        DenseboxHead:
          total_stride: 8
          score_size: &SCORE_SIZE_TEST 31 #19
          x_size: &X_SIZE_TEST 399 #303
          num_conv3x3: &NUM_CONV3x3 2
          head_conv_bn: [False, False]
      task_model:
        name: "SiamTrack"
        SiamTrack:
          pretrain_model_path: "models/siamfcpp-googlenet-vot.pkl"
          trt_mode: False
          trt_fea_model_path: "models/siamfcpp-googlenet-vot-fea.trt"
          trt_track_model_path: "models/siamfcpp-googlenet-vot-track.trt"
    pipeline:
      name: "SiamFCppTracker"
      SiamFCppTracker:
        test_lr: 0.5093639624865886
        window_influence: 0.2444928917567117
        penalty_k: 0.06721247775471334
        x_size: *X_SIZE_TEST
        num_conv3x3: *NUM_CONV3x3
    tester:
      names: ["VOTTester",]
      VOTTester:
        exp_name: *TEST_NAME
        exp_save: *TEST_SAVE
        device_num: 1
        dataset_names: ["VOT2018"]
